# Generated manually for ARDE Leads / Prospección
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='BusquedaProspectos', fields=[('id',models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('creado_el',models.DateTimeField(auto_now_add=True)),('actualizado_el',models.DateTimeField(auto_now=True)),('consulta',models.CharField(max_length=180)),('ciudad',models.CharField(blank=True,max_length=120)),('zona',models.CharField(blank=True,max_length=160)),('latitud',models.DecimalField(blank=True,decimal_places=7,max_digits=10,null=True)),('longitud',models.DecimalField(blank=True,decimal_places=7,max_digits=10,null=True)),('radio_metros',models.PositiveIntegerField(default=3000)),('modo_busqueda',models.CharField(choices=[('quick','Rápida'),('balanced','Equilibrada'),('deep','Profunda')],default='balanced',max_length=16)),('campos_solicitados',models.TextField(blank=True)),('max_resultados',models.PositiveIntegerField(default=60)),('estado',models.CharField(choices=[('draft','Borrador'),('queued','En cola'),('running','En ejecución'),('completed','Completada'),('failed','Fallida'),('cancelled','Cancelada')],db_index=True,default='draft',max_length=16)),('solicitudes_estimadas',models.PositiveIntegerField(default=0)),('solicitudes_reales',models.PositiveIntegerField(default=0)),('resultados_encontrados',models.PositiveIntegerField(default=0)),('prospectos_creados',models.PositiveIntegerField(default=0)),('prospectos_actualizados',models.PositiveIntegerField(default=0)),('duplicados_detectados',models.PositiveIntegerField(default=0)),('errores_api',models.PositiveIntegerField(default=0)),('mensaje_error',models.TextField(blank=True)),('bitacora_api',models.JSONField(blank=True,default=list)),('iniciado_el',models.DateTimeField(blank=True,null=True)),('finalizado_el',models.DateTimeField(blank=True,null=True)),('creado_por',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))], options={'verbose_name':'búsqueda de prospectos','verbose_name_plural':'búsquedas de prospectos'}),
        migrations.CreateModel(name='PlantillaMensaje', fields=[('id',models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('creado_el',models.DateTimeField(auto_now_add=True)),('actualizado_el',models.DateTimeField(auto_now=True)),('nombre',models.CharField(max_length=160)),('rubro_objetivo',models.CharField(blank=True,max_length=120)),('tipo_oferta',models.CharField(blank=True,max_length=120)),('cuerpo',models.TextField()),('activa',models.BooleanField(default=True))]),
        migrations.CreateModel(name='Prospecto', fields=[('id',models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('creado_el',models.DateTimeField(auto_now_add=True)),('actualizado_el',models.DateTimeField(auto_now=True)),('place_id',models.CharField(max_length=255,unique=True)),('nombre',models.CharField(max_length=255)),('nombre_normalizado',models.CharField(blank=True,db_index=True,max_length=255)),('rubro',models.CharField(blank=True,max_length=100)),('tipos',models.JSONField(blank=True,default=list)),('estado_google',models.CharField(blank=True,max_length=80)),('direccion_formateada',models.TextField(blank=True)),('direccion_corta',models.CharField(blank=True,max_length=255)),('ciudad',models.CharField(blank=True,max_length=120)),('zona',models.CharField(blank=True,max_length=160)),('latitud',models.DecimalField(blank=True,decimal_places=7,max_digits=10,null=True)),('longitud',models.DecimalField(blank=True,decimal_places=7,max_digits=10,null=True)),('telefono_nacional',models.CharField(blank=True,max_length=80)),('telefono_internacional',models.CharField(blank=True,max_length=80)),('telefono_normalizado',models.CharField(blank=True,db_index=True,max_length=40)),('sitio_web',models.URLField(blank=True,max_length=500)),('url_google_maps',models.URLField(blank=True,max_length=500)),('calificacion',models.DecimalField(blank=True,decimal_places=2,max_digits=3,null=True)),('cantidad_resenas',models.PositiveIntegerField(default=0)),('tiene_web',models.BooleanField(db_index=True,default=False)),('tiene_telefono',models.BooleanField(db_index=True,default=False)),('es_posible_duplicado',models.BooleanField(db_index=True,default=False)),('clave_grupo_duplicado',models.CharField(blank=True,db_index=True,max_length=255)),('puntaje_oportunidad',models.PositiveSmallIntegerField(default=0)),('puntaje_contactabilidad',models.PositiveSmallIntegerField(default=0)),('puntaje_confianza',models.PositiveSmallIntegerField(default=0)),('puntaje_total',models.PositiveSmallIntegerField(default=0)),('motivos_puntaje',models.JSONField(blank=True,default=list)),('estado_comercial',models.CharField(choices=[('new','Nuevo'),('review','Revisar'),('contacted','Contactado'),('replied','Respondió'),('interested','Interesado'),('won','Ganado'),('lost','Perdido'),('discarded','Descartado'),('do_not_contact','No contactar')],db_index=True,default='new',max_length=24)),('ultimo_contacto_el',models.DateTimeField(blank=True,null=True)),('proximo_seguimiento_el',models.DateTimeField(blank=True,null=True)),('notas',models.TextField(blank=True)),('busqueda_origen',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='prospectos',to='prospeccion.busquedaprospectos'))], options={'verbose_name':'prospecto','verbose_name_plural':'prospectos'}),
        migrations.CreateModel(name='RegistroContacto', fields=[('id',models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('canal',models.CharField(choices=[('whatsapp','WhatsApp'),('telefono','Teléfono'),('email','Email'),('otro','Otro')],default='whatsapp',max_length=16)),('direccion',models.CharField(choices=[('saliente','Saliente'),('entrante','Entrante')],default='saliente',max_length=16)),('plantilla_mensaje',models.CharField(blank=True,max_length=180)),('cuerpo_mensaje',models.TextField(blank=True)),('estado',models.CharField(choices=[('borrador','Borrador'),('copiado','Copiado'),('whatsapp_abierto','WhatsApp abierto'),('enviado_manual','Enviado manualmente'),('respondio','Respondió'),('fallo','Falló')],default='borrador',max_length=24)),('creado_el',models.DateTimeField(auto_now_add=True)),('creado_por',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('prospecto',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='registros_contacto',to='prospeccion.prospecto'))]),
        migrations.CreateModel(name='Campania', fields=[('id',models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('creado_el',models.DateTimeField(auto_now_add=True)),('actualizado_el',models.DateTimeField(auto_now=True)),('nombre',models.CharField(max_length=160)),('rubro',models.CharField(blank=True,max_length=120)),('zona',models.CharField(blank=True,max_length=160)),('tipo_oferta',models.CharField(blank=True,max_length=120)),('estado',models.CharField(choices=[('draft','Borrador'),('active','Activa'),('paused','Pausada'),('completed','Completada')],default='draft',max_length=16)),('plantilla',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='prospeccion.plantillamensaje'))]),
        migrations.CreateModel(name='ProspectoCampania', fields=[('id',models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('estado',models.CharField(default='nuevo',max_length=32)),('agregado_el',models.DateTimeField(auto_now_add=True)),('campania',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='prospeccion.campania')),('prospecto',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='prospeccion.prospecto'))], options={'unique_together':{('campania','prospecto')}}),
        migrations.AddField(model_name='campania', name='prospectos', field=models.ManyToManyField(related_name='campanias', through='prospeccion.ProspectoCampania', to='prospeccion.prospecto')),
    ]
