# Generated manually for ARDE Leads
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='LeadSearch', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('query', models.CharField(max_length=180)),('city', models.CharField(blank=True, max_length=120)),('area_label', models.CharField(blank=True, max_length=160)),('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),('radius_meters', models.PositiveIntegerField(default=3000)),('search_mode', models.CharField(choices=[('quick','Quick'),('balanced','Balanced'),('deep','Deep')], default='balanced', max_length=16)),('requested_fields', models.TextField(blank=True)),('max_results', models.PositiveIntegerField(default=60)),('status', models.CharField(choices=[('draft','Draft'),('queued','Queued'),('running','Running'),('completed','Completed'),('failed','Failed'),('cancelled','Cancelled')], db_index=True, default='draft', max_length=16)),('estimated_requests', models.PositiveIntegerField(default=0)),('actual_requests', models.PositiveIntegerField(default=0)),('results_found', models.PositiveIntegerField(default=0)),('leads_created', models.PositiveIntegerField(default=0)),('leads_updated', models.PositiveIntegerField(default=0)),('duplicates_detected', models.PositiveIntegerField(default=0)),('api_error_count', models.PositiveIntegerField(default=0)),('error_message', models.TextField(blank=True)),('audit_log', models.JSONField(blank=True, default=list)),('started_at', models.DateTimeField(blank=True, null=True)),('finished_at', models.DateTimeField(blank=True, null=True)),('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='MessageTemplate', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('name', models.CharField(max_length=160)),('target_business_type', models.CharField(blank=True, max_length=120)),('offer_type', models.CharField(blank=True, max_length=120)),('body', models.TextField()),('is_active', models.BooleanField(default=True))]),
        migrations.CreateModel(name='Lead', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('place_id', models.CharField(max_length=255, unique=True)),('name', models.CharField(max_length=255)),('normalized_name', models.CharField(blank=True, db_index=True, max_length=255)),('primary_type', models.CharField(blank=True, max_length=100)),('types', models.JSONField(blank=True, default=list)),('business_status', models.CharField(blank=True, max_length=80)),('formatted_address', models.TextField(blank=True)),('short_formatted_address', models.CharField(blank=True, max_length=255)),('city', models.CharField(blank=True, max_length=120)),('area_label', models.CharField(blank=True, max_length=160)),('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),('national_phone_number', models.CharField(blank=True, max_length=80)),('international_phone_number', models.CharField(blank=True, max_length=80)),('phone_normalized', models.CharField(blank=True, db_index=True, max_length=40)),('website_uri', models.URLField(blank=True, max_length=500)),('google_maps_uri', models.URLField(blank=True, max_length=500)),('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),('user_rating_count', models.PositiveIntegerField(default=0)),('has_website', models.BooleanField(db_index=True, default=False)),('has_phone', models.BooleanField(db_index=True, default=False)),('is_possible_duplicate', models.BooleanField(db_index=True, default=False)),('duplicate_group_key', models.CharField(blank=True, db_index=True, max_length=255)),('opportunity_score', models.PositiveSmallIntegerField(default=0)),('contactability_score', models.PositiveSmallIntegerField(default=0)),('confidence_score', models.PositiveSmallIntegerField(default=0)),('total_score', models.PositiveSmallIntegerField(default=0)),('score_reasons', models.JSONField(blank=True, default=list)),('commercial_status', models.CharField(choices=[('new','Nuevo'),('review','Revisar'),('contacted','Contactado'),('replied','Respondió'),('interested','Interesado'),('won','Ganado'),('lost','Perdido'),('discarded','Descartado'),('do_not_contact','No contactar')], db_index=True, default='new', max_length=24)),('last_contacted_at', models.DateTimeField(blank=True, null=True)),('next_follow_up_at', models.DateTimeField(blank=True, null=True)),('notes', models.TextField(blank=True)),('source_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leadfinder.leadsearch'))]),
        migrations.CreateModel(name='LeadContactLog', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('channel', models.CharField(choices=[('whatsapp','WhatsApp'),('phone','Teléfono'),('email','Email'),('other','Otro')], default='whatsapp', max_length=16)),('direction', models.CharField(choices=[('outbound','Saliente'),('inbound','Entrante')], default='outbound', max_length=16)),('message_template', models.CharField(blank=True, max_length=180)),('message_body', models.TextField(blank=True)),('status', models.CharField(choices=[('drafted','Borrador'),('copied','Copiado'),('opened_whatsapp','WhatsApp abierto'),('sent_manually','Enviado manual'),('replied','Respondió'),('failed','Falló')], default='drafted', max_length=24)),('created_at', models.DateTimeField(auto_now_add=True)),('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='leadfinder.lead'))]),
        migrations.CreateModel(name='Campaign', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('name', models.CharField(max_length=160)),('business_type', models.CharField(blank=True, max_length=120)),('area_label', models.CharField(blank=True, max_length=160)),('offer_type', models.CharField(blank=True, max_length=120)),('status', models.CharField(choices=[('draft','Draft'),('active','Activa'),('paused','Pausada'),('completed','Completada')], default='draft', max_length=16)),('message_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadfinder.messagetemplate'))]),
        migrations.CreateModel(name='CampaignLead', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('status', models.CharField(default='new', max_length=32)),('added_at', models.DateTimeField(auto_now_add=True)),('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadfinder.campaign')),('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadfinder.lead'))], options={'unique_together': {('campaign','lead')}}),
        migrations.AddField(model_name='campaign', name='leads', field=models.ManyToManyField(related_name='campaigns', through='leadfinder.CampaignLead', to='leadfinder.lead')),
    ]
